export const ENTRANCE_LIST = {
  d8: "Turtle Rock",
  phone_d8: "Turtle Rock Phone Booth",
  fire_cave_exit: "Fire Cave Exit",
  fire_cave_entrance: "Fire Cave Entrance",
  madbatter_taltal: "Mad Batter - TalTal Heights",
  left_taltal_entrance: "Left TalTal Entrance",
  obstacle_cave_entrance: "Obstacle Cave Entrance",
  left_to_right_taltalentrance: "Left to Right TalTal Entrance",
  obstacle_cave_outside_chest: "Obstacle Cave Outside CHest",
  obstacle_cave_exit: "Obstacle Cave Exit",
  papahl_entrance: "Way to Papahl Entrance",
  papahl_exit: "Way to Papahl Exit",
  rooster_house: "Rooster House",
  bird_cave: "Bird Cave",
  multichest_left: "Multichest Left",
  multichest_right: "Multichest Right",
  multichest_top: "Multichest Top",
  right_taltal_connector1: "Right TalTal Connector 1",
  right_taltal_connector2: "Right TalTal Connector 2",
  right_taltal_connector3: "Right TalTal Connector 3",
  right_taltal_connector4: "Right TalTal Connector 4",
  right_taltal_connector5: "Right TalTal Connector 5",
  right_taltal_connector6: "Right TalTal Connector 6",
  right_fairy: "Right Fairy",
  d7: "Eagle's Tower",
  writes_cave_left: "Write's Cave - Left",
  writes_cave_right: "Write's Cave - Right",
  writes_house: "Write's House",
  writes_phone: "Write's Phone Booth",
  d2: "Bottle Grotto",
  moblin_cave: "Moblin Cave",
  photo_house: "Photo House",
  mambo: "Mambo's Cave",
  d4: "Angler's Tunnel",
  d4_connector: "Angler's Tunnel Connector Entrance",
  d4_connector_exit: "Angler's Tunnel Connector Exit",
  heartpiece_swim_cave: "Heartpiece Swim Cave",
  raft_return_exit: "Raft Return Exit",
  raft_house: "Raft House",
  raft_return_enter: "Raft Return Entrance",
  hookshot_cave: "Hookshot Cave",
  toadstool_exit: "Toadstool Exit",
  forest_madbatter: "Mad Batter - Forest",
  toadstool_entrance: "Toadstool Entrance",
  crazy_tracy: "Crazy Tracy",
  witch: "Witch's Hut",
  graveyard_cave_left: "Graveyard Cave Left",
  graveyard_cave_right: "Graveyard Cave Right",
  d0: "Color Dungeon",
  castle_jump_cave: "Castle Jump Cave",
  castle_main_entrance: "Castle Main Entrance",
  castle_upper_left: "Castle Upper Left",
  castle_upper_right: "Castle Upper Right",
  castle_secret_exit: "Castle Secret Exit",
  castle_secret_entrance: "Castle Secret Entrance",
  castle_phone: "Castle Phone Booth",
  papahl_house_left: "Papahl House Left",
  papahl_house_right: "Papahl House Right",
  dream_hut: "Dream Hut",
  rooster_grave: "Rooster Grave",
  shop: "Shop",
  madambowwow: "Madam Bowwow's House",
  kennel: "Dog Kennel",
  start_house: "Tarin's House",
  library: "Library",
  ulrira: "Grandpa Ulrira's House",
  mabe_phone: "Mabe Village Phone Booth",
  trendy_shop: "Trendy Shop",
  prairie_left_phone: "Prarie Left Cave 1",
  prairie_left_cave1: "Prarie Left Cave 2",
  prairie_left_cave2: "Prarie Left Cave 3",
  prairie_left_fairy: "Prarie Left Fairy",
  mamu: "Mamu's Cave",
  d3: "Key Cavern",
  prairie_right_phone: "Prairie Right Phone Booth",
  seashell_mansion: "Seashell Mansion",
  prairie_right_cave_top: "Prairie Right Cave Top",
  prairie_right_cave_bottom: "Prairie Right Cave Bottom",
  prairie_right_cave_high: "Prairie Right Cave High Exit",
  prairie_to_animal_connector: "Prairie to Animal Village",
  animal_to_prairie_connector: "Animal Village to Prairie",
  d6: "Face Shrine",
  d6_connector_exit: "Face Shrine Connector Exit",
  d6_connector_entrance: "Face Shrine Connector Entrance",
  armos_fairy: "Armos Fairy",
  armos_maze_cave: "Armos Maze Cave",
  armos_temple: "Armos Temple",
  d1: "Tail Cave",
  boomerang_cave: "Boomerang Trading Cave",
  banana_seller: "Banana Seller",
  ghost_house: "Ghost House",
  richard_house: "Richard's House",
  richard_maze: "Richard's Maze Entrance",
  prairie_low_phone: "Prairie Lower Phone Booth",
  prairie_madbatter_connector_entrance: "Prairie Mad Batter Connector Entrance",
  prairie_madbatter_connector_exit: "Prairie Mad Batter Connector Exit",
  prairie_madbatter: "Prairie Mad Batter",
  d5: "Catfish's Maw",
  animal_phone: "Animal Village Phone Booth",
  animal_house1: "Animal Village - Bunnies",
  animal_house2: "Animal Village - Painter",
  animal_house3: "Animal Village - Goat",
  animal_house4: "Animal Village - Empty",
  animal_house5: "Animal Village - Bear Cook",
  animal_cave: "Animal Village - Cave",
  desert_cave: "Desert Cave",
} as const;

export default interface Entrance {
  from: typeof ENTRANCE_LIST[keyof typeof ENTRANCE_LIST];
  to: typeof ENTRANCE_LIST[keyof typeof ENTRANCE_LIST];
}
